# Generated by Django 5.2 on 2025-05-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenDayRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100, verbose_name='ФИО родителя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
